---

common_packages_vagrant:
   - binutils
   - kernel-devel                                                                                                 
   - kernel-headers
   - libgomp
   - make
   - patch
   - gcc
   - glibc-headers
   - glibc-devel
   - perl
   - wget
   - elfutils-libelf-devel

kernel_version: 4.18.0-193.el8.x86_64
system_version: 8.2.2004

...
