---

- name: OPERATING SYSTEM | Add Motd
  template: src=motd.sh dest=/etc/motd.sh force=yes owner=root group=root mode=0755

- name: OPERATING SYSTEM | Change /etc/profile
  lineinfile: dest=/etc/profile line={{ item }}
  with_items:
    - 'export HISTTIMEFORMAT="%d/%m/%Y - %H:%M:%S - "'
    - 'export HISTSIZE="5000"'
    - 'export HISTFILESIZE="5000"'
    - 'export TMOUT="120"'
    - 'alias ls="ls -lh --color"'
    - 'alias grep="grep --color"'
    - 'alias rm="rm -i"'
    - '/etc/motd.sh'

- name: OPERATING SYSTEM | Importing key "https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"
  rpm_key: key=https://www.elrepo.org/RPM-GPG-KEY-elrepo.org state=present

- name: OPERATING SYSTEM | Installing epel-release and elrepo
  yum:    
    name: 
      - epel-release
      - https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    state: present

- name: OPERATING SYSTEM | Enable PowerTool Repository
  replace:
    dest=/etc/yum.repos.d/CentOS-PowerTools.repo
    regexp='enabled=0'
    replace='enabled=1'
  when: ansible_distribution_major_version == "8"

- name: OPERATING SYSTEM | Update System
  yum: 
    name: '*' 
    state: latest 
    update_cache: yes 
    exclude: grub2* shim* mokutil
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: OPERATING SYSTEM | Install common packages
  yum: name={{ common_packages_ctos }} state=latest
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: SSH | Setting basic SSH options
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp={{ item.regexp }}
    line={{ item.line }}
    backrefs=yes
  with_items:
    - { regexp: 'Port 22', line: 'Port 62222' }
    - { regexp: 'PermitRootLogin yes', line: 'PermitRootLogin no' }
    - { regexp: '#Banner none', line: 'Banner /etc/ssh/banner_ssh' }
    - { regexp: '#StrictModes yes', line: 'StrictModes yes' }
    - { regexp: 'X11Forwarding yes', line: 'X11Forwarding no' }
  notify:
    - Restart sshd

- name: FIREWALL | Enable allow SSH port      
  firewalld:
    port: 62222/tcp
    permanent: yes
    immediate: yes
    state: enabled
    
- name: SSH | Add SSH Banner
  copy: src=banner_ssh dest=/etc/ssh/banner_ssh 

...
